allowBuilds:
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  core-js: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
